platform:
- x64
- Win32
environment:
  matrix:
    - PYTHON: 27
    - PYTHON: 35
    - PYTHON: 36
    - PYTHON: 37
  pypipassword:
    # https://ci.appveyor.com/tools/encrypt
    secure: OTDy8BHbSmZE4K0JvfAeYQ==
install:
- ps: |
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;C:\Users\appveyor\AppData\Roaming\Python\Scripts;$env:PATH"
    }
build_script:
- cmd: pip install --user -e .[test]
test_script:
- cmd: python setup.py test
deploy_script: 
- ps: |
    if ($env:APPVEYOR_REPO_BRANCH -ne "master" -or $env:APPVEYOR_REPO_TAG -ne "true") { return }
    # Specify account details for PyPI
    echo [distutils]                                  > $env:USERPROFILE\\.pypirc
    echo index-servers =                             >> $env:USERPROFILE\\.pypirc
    echo     pypi                                    >> $env:USERPROFILE\\.pypirc
    echo [pypi]                                      >> $env:USERPROFILE\\.pypirc
    echo repository=https://pypi.python.org/pypi     >> $env:USERPROFILE\\.pypirc
    echo username=scottgigante                       >> $env:USERPROFILE\\.pypirc
    echo password=$env:pypipassword                  >> $env:USERPROFILE\\.pypirc
    # Workaround required to ensure setup.py finds the .pypirc under Windows
    $env:HOME=$env:USERPROFILE
    # Install wheel-building support
    pip install --user wheel twine
    # Build wheel and upload
    python setup.py sdist bdist_wheel
    twine upload -r pypi dist/*
