name: pre-commit
on:
  push:
    branches-ignore:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-

      - name: Run pre-commit
        id: precommit
        continue-on-error: true
        uses: pre-commit/action@v3.0.0

      - name: Commit files
        if: "steps.precommit.outcome == 'failure'"
        run: |
          git checkout -- .github/workflows
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "pre-commit"
          fi

      - name: Push changes
        if: "steps.precommit.outcome == 'failure'"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Check pre-commit
        if: "steps.precommit.outcome == 'failure'"
        continue-on-error: false
        uses: pre-commit/action@v3.0.0
