name: Unit Tests

on:
  push:
    branches-ignore:
      - 'test_deploy'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run_tester:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: '3.11', os: ubuntu-latest, python: '3.11' }
        - {name: '3.10', os: ubuntu-latest, python: '3.10' }
        - {name: '3.9', os: ubuntu-latest, python: '3.9' }
        - {name: '3.8', os: ubuntu-latest, python: '3.8' }
        - {name: '3.7', os: ubuntu-latest, python: '3.7' }

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.config.python }}

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{runner.os}}-pip-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
        restore-keys: ${{runner.os}}-pip-${{ env.pythonLocation }}-

    - name: Install package & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U wheel setuptools
        pip install -U .[test]
        python -c "import tasklogger"

    - name: Run tests
      run: nose2 -vvv

    - name: Coveralls
      uses: coverallsapp/github-action@v2
