name: Unit Tests

on:
  push:
    branches-ignore:
      - 'test_deploy'
  pull_request:
    branches:
      - '*'

jobs:

  run_tester:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: '3.9', os: ubuntu-latest, python: '3.9' }
        - {name: '3.8', os: ubuntu-latest, python: '3.8' }
        - {name: '3.7', os: ubuntu-latest, python: '3.7' }
        - {name: '3.6', os: ubuntu-latest, python: '3.6' }
        - {name: '3.5', os: ubuntu-latest, python: '3.5' }

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{runner.os}}-pip-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
        restore-keys: ${{runner.os}}-pip-${{ env.pythonLocation }}-

    - name: Install package & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U wheel setuptools
        pip install -U .[test]
        python -c "import tasklogger"

    - name: Run tests
      run: nose2 -vvv

    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: |
        coveralls

    - name: Upload check results on fail
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check

